swagger: '2.0'
info:
  version: 1.0.0
  title: A Plus Workflow API
  description: The best api in the world.
schemes:
  - https
basePath: /v1
produces:
  - application/vnd.api+json
paths:
  /tickets:
    get:
      parameters:
        - name: limit
          in: query
          description: the number of tickets to return
          type: integer
          default: 100
      responses:
        200:
          description: List all tickets 
          schema:
            title: Tickets
            type: array
            items:
              $ref: '#/definitions/Ticket'
definitions:
  Ticket:
    type: object
    properties:
      id:
        type: string
        format: uuid
      name:
        type: string
      description:
        type: string